/**
 * Shared non-medical-advice disclosure wrapper for any AI-generated explanation.
 * Constitution Principle IV (NON-NEGOTIABLE): every AI response must be clearly labeled as
 * informational, never diagnostic, and every surface must show its source (local/external).
 * Screens must render AI text through this component rather than a bare <Text>, so the label
 * can never be silently dropped by a future call site.
 */
import { StyleSheet, Text, View } from "react-native";

import type { AiSource } from "../models/types";

interface AiDisclosureProps {
  responseText: string;
  aiSource: AiSource;
  externalProviderName?: string;
}

export function AiDisclosure({ responseText, aiSource, externalProviderName }: AiDisclosureProps) {
  const sourceLabel =
    aiSource === "external"
      ? `Generated by ${externalProviderName ?? "an external AI provider"} you opted in to`
      : "Generated on-device, no data left your device";

  return (
    <View style={styles.container}>
      <Text style={styles.badge}>Not medical advice — informational only</Text>
      <Text style={styles.responseText}>{responseText}</Text>
      <Text style={styles.sourceLabel}>{sourceLabel}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderWidth: 1,
    borderColor: "#D9A400",
    backgroundColor: "#FFF8E6",
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  badge: {
    fontSize: 12,
    fontWeight: "700",
    color: "#8A6100",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  responseText: {
    fontSize: 15,
    color: "#1A1A1A",
    lineHeight: 21,
  },
  sourceLabel: {
    fontSize: 12,
    color: "#6B6B6B",
  },
});
